[package]
name = "schism"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schism-components = { path = "schism-components" }
schism-solution = { path = "schism-solution" }